#This workflow runs the tests in the test projects to make sure the generator works as a library where it is a Node dependency along with the template.
name: Test using test project

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  check-files:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.check.outputs.should_skip }}
    steps:
      - name: Check for skippable files
        id: check
        env:
          PR_FILES: ${{ toJson(github.event.pull_request.files.*.path) }}
        run: |
          SKIPPABLE_FILES=('README.md' 'docs/**' '.github/**' 'CONTRIBUTING.md' 'Development.md')
          SKIP=false
          
          for file in "${SKIPPABLE_FILES[@]}"; do
            if echo "$PR_FILES" | grep -q "$file"; then
              SKIP=true
              break
            fi
          done
          
          echo "should_skip=$SKIP" >> $GITHUB_OUTPUT

  test:
    needs: check-files
    if: >
      github.event.pull_request.draft == false &&
      needs.check-files.outputs.should_skip != 'true' &&
      !(
        (github.actor == 'asyncapi-bot' && (
          startsWith(github.event.pull_request.title, 'ci: update of files from global .github repo') || 
          startsWith(github.event.pull_request.title, 'chore(release):')
        )) ||
        (github.actor == 'asyncapi-bot-eve' && (
          startsWith(github.event.pull_request.title, 'ci: update of files from global .github repo') || 
          startsWith(github.event.pull_request.title, 'chore(release):')
        )) ||
        (github.actor == 'allcontributors[bot]' && 
          startsWith(github.event.pull_request.title, 'docs: add')
        )
      )
    name: Test generator as dependency with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["18", "20"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run test
        run: NODE_IMAGE_TAG=${{ matrix.node }} docker compose up --abort-on-container-exit --remove-orphans --force-recreate
        working-directory: ./apps/generator/test/test-project
